src/api/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from portal import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/ooo/', views.OutOfOfficeRequesetView.as_view(), name='ooo-request'),
    path('accounts/profile/', views.ProfileView.as_view(), name='profile'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns.append(url(r'pages/', include('pages.urls')))

src/portal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from datetime import date, datetime
from numpy import busday_count



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to='pic_folder/')
    joined = models.DateField()
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    email = models.EmailField(null=True)
    position = models.CharField(max_length=100)
    location = models.CharField(max_length=50, default='Belarus, Minsk')


    def vacation_left_p(self):
        vacation_days_per_year_limit = 19
        vacation_pecent_left = int(self.vacation_left() / vacation_days_per_year_limit * 100)
        return vacation_pecent_left

    def vacation_left(self, ):
        start_date = self.joined
        holidays = []

        def get_years_ranges(start, end):
            delta = end.year - start.year
            years = [start.year + i for i in range(delta + 1)]
            number_of_years = len(years)
            start_dates = []
            end_dates = []
            if number_of_years == 1:
                start_dates.append(start.strftime("%Y-%m-%d"))
                end_dates.append(end.strftime("%Y-%m-%d"))
            elif number_of_years >= 2:
                for year in years:
                    start_dates.append(date(year=year, day=1, month=1))
                    end_dates.append(date(year=year, day=31, month=12))
                if start_dates[0] < start:
                    start_dates[0] = start
                if end_dates[-1] > end:
                    end_dates[-1] = end
            return start_dates, end_dates

        year_k = 0.0689

        today = datetime.now().date()
        start_dates, end_dates = get_years_ranges(start_date, today)

        earned_vacation_days = 0

        for i in range(len(start_dates)):
            busines_days_count = busday_count(
                start_dates[i].strftime("%Y-%m-%d"),
                end_dates[i].strftime("%Y-%m-%d"),
                holidays=holidays
            )
            earned_vacation_days += busines_days_count * year_k

        vacation_requests = OutOfOfficeRequest.objects.filter(
            requester=self.user,
            status=OutOfOfficeRequest.APPROVED,
            request_type=OutOfOfficeRequest.VACATION
        )

        used_days = 0

        for vacation_request in vacation_requests:
            busines_days_count = busday_count(
                vacation_request.from_date.strftime("%Y-%m-%d"),
                vacation_request.till_date.strftime("%Y-%m-%d"),
                holidays=holidays
            )
            used_days += busines_days_count

        vacation_days_left = int(round(earned_vacation_days)) - used_days
        return vacation_days_left

    def day_off_left_p(self):
        day_off_per_year_limit = 5
        day_off_pecent_left = int(self.day_off_left() / day_off_per_year_limit * 100)
        return day_off_pecent_left

    def day_off_left(self):
        day_off_per_year_limit = 5
        holidays = []

        today = datetime.now().date()
        dayoff_requests = OutOfOfficeRequest.objects.filter(
            requester=self.user,
            from_date__year=today.year,
            status=OutOfOfficeRequest.APPROVED,
            request_type=OutOfOfficeRequest.DAY_OFF
        )
        used_days = 0
        for dayoff in dayoff_requests:
            time_delta = dayoff.till_date-dayoff.from_date
            dayoff_length = time_delta.days + 1
            used_days += dayoff_length

        for vacation_request in dayoff_requests:
            busines_days_count = busday_count(
                vacation_request.from_date.strftime("%Y-%m-%d"),
                vacation_request.till_date.strftime("%Y-%m-%d"),
                holidays=holidays
            )
            used_days += busines_days_count

        day_off_per_left = day_off_per_year_limit - used_days

        return day_off_per_left


class OutOfOfficeRequest(models.Model):
    VACATION = _('Vacation')
    DAY_OFF = _('Day-off')

    REQUEST_TYPE_CHOICES = (
        ('Vacation', VACATION),
        ('Day-off', DAY_OFF),
    )
    PENDING = _('Pending')
    APPROVED = _('Approved')
    REJECTED = _('Rejected')

    STATUS_TYPE_CHOICES = (
        ('Pending', PENDING),
        ('Approved', APPROVED),
        ('Rejected', REJECTED)
    )

    requester = models.ForeignKey(User, on_delete=models.CASCADE)
    from_date = models.DateField()
    till_date = models.DateField()
    message = models.CharField(max_length=255)
    request_type = models.CharField(max_length=30, choices=REQUEST_TYPE_CHOICES)
    status = models.CharField(max_length=25, choices=STATUS_TYPE_CHOICES, default=PENDING)


class Holiday(models.Model):
    date = models.DateField()
    annual = models.BooleanField(default=False)

src/portal/forms.py
from django import forms
from portal.models import OutOfOfficeRequest
from django.conf import settings


class OutOfOfficeRequestForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea)
    from_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    till_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)

    class Meta:
        model = OutOfOfficeRequest
        fields = ['from_date', 'till_date', 'message', 'request_type']

    def __init__(self, *args, **kwargs):
        self.context = kwargs.pop("context")
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(OutOfOfficeRequestForm, self).clean()
        vacation_left = self.context['request'].user.profile.vacation_left()

        from_date = cleaned_data.get("from_date")
        till_date = cleaned_data.get("till_date")

        time_delta = till_date - from_date


        return self.cleaned_data

src/portal/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from portal.forms import OutOfOfficeRequestForm
from portal.models import OutOfOfficeRequest

class ProfileView(View):
    def get(self, request, *args, **kwargs):
        profile = request.user.profile
        vacation = profile.vacation_left()
        return render(request, 'profile.html', {
            'profile': profile,
            'vacation': vacation,
        })


class OutOfOfficeRequesetView(View):

    def get(self, request, *args, **kwargs):
        requests = OutOfOfficeRequest.objects.filter(requester=request.user)
        form = OutOfOfficeRequestForm(context={'request': request})
        return render(request, 'out-of-office-request.html', {
            'form': form,
            'requests': requests
        })

    def post(self, request, *args, **kwargs):

        form = OutOfOfficeRequestForm(request.POST, context={'request': request})

        if form.is_valid():
            request_object = form.save(commit=False)
            request_object.requester = request.user
            request_object.save()
        requests = OutOfOfficeRequest.objects.filter(requester=request.user)

        return render(request, 'out-of-office-request.html', {
            'form': form,
            'requests': requests
        })

src/templates/includes/footer.html
            <footer class="footer-3 text-center-xs space--xs ">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <img alt="Image" class="logo" src="img/logo-dark.png" />
                            <ul class="list-inline list--hover">
                                <li class="list-inline-item">
                                    <a href="#">
                                        <span class="type--fine-print">Get Started</span>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#">
                                        <span class="type--fine-print">help@stack.io</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6 text-right text-center-xs">
                            <ul class="social-list list-inline list--hover">
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="socicon socicon-google icon icon--xs"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="socicon socicon-twitter icon icon--xs"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="socicon socicon-facebook icon icon--xs"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="socicon socicon-instagram icon icon--xs"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!--end of row-->
                    <div class="row">
                        <div class="col-md-6">
                            <p class="type--fine-print">
                                Supercharge your web workflow
                            </p>
                        </div>
                        <div class="col-md-6 text-right text-center-xs">
                            <span class="type--fine-print">&copy;
                                <span class="update-year"></span> Stack Inc.</span>
                            <a class="type--fine-print" href="#">Privacy Policy</a>
                            <a class="type--fine-print" href="#">Legal</a>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </footer>

src/templates/out-of-office-request.html
{% extends 'base.html' %}
{% load static %}

{% block main_container %}
    <div class="main-container">
        <section class="space--sm">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <form method="post" novalidate>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-6">
                                    <label for="id_from_date">From date:</label>
                                    <input class="datepicker" type="text" name="from_date" required id="id_from_date">
                                </div>
                                <div class="col-6">
                                    <label for="id_till_date">Till date:</label>
                                    <input class="datepicker" type="text" name="till_date" required id="id_till_date">
                                </div>
                                <div class="col-12">
                                    <label for="id_message">Message:</label>
                                    <textarea name="message" cols="40" rows="10" required id="id_message"></textarea>
                                </div>
                                <div class="col-12">
                                    <div class="input-select">
                                        <select name="request_type" required id="id_request_type">
                                            <option value="Vacation" selected>Vacation</option>
                                            <option value="Day-off">Day-off</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-4">
                                    <input type="submit" value="Submit">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>


    <section class="space--sm">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-10">

                        <table class="border--round table--alternate-row">
	<thead>
		<tr>
			<th>From</th>
			<th>Till</th>
			<th>Message</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>
    {% for request in requests %}
		<tr>
			<td>{{ request.from_date }}</td>
			<td>{{ request.till_date }}</td>
			<td>{{ request.message }}</td>
			<td>{{ request.status }}</td>
		</tr>
    {% endfor %}
	</tbody>
</table>
                    </div>
                </div>
            </div>
        </section>



    </div>
{% endblock main_container %}

src/templates/pages/article.html
{% extends 'base.html' %}
{% load pages_tags i18n static %}
{% load_pages %}


{% block main_container %}
    <div class="main-container">
        <section>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-8">
                        <article>
                            <div class="article__title text-center">
                                <h1 class="h2">{% show_content current_page "title" %}</h1>
                            </div>
                            <!--end article title-->
                            <div class="article__body">

                                {% page_has_content 'body-image' %}
                                    <img src="/media/{% imageplaceholder 'body-image' %}">
                                {% end_page_has_content %}

                                {% placeholder body with RichTextarea %}
                            </div>

                        </article>
                        <!--end item-->
                    </div>
                </div>
                <!--end of row-->
            </div>
            <!--end of container-->
        </section>
    </div>
{% endblock main_container %}

src/templates/pages/index.html
{% extends 'base.html' %}
{% load pages_tags i18n static %}
{% load_pages %}

{% block title %}{% show_content current_page "title" %}{% endblock title %}


{% block main_container %}
    {{ pages }}
    <div class="main-container">
        <section>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-8">
                        <article>
                            <div class="article__title text-center">
                                <h1 class="h2">{% show_content current_page "title" %}</h1>
                            </div>
                            <!--end article title-->
                            <div class="article__body">

                                {% page_has_content 'body-image' %}
                                    <img src="/media/{% imageplaceholder 'body-image' %}">
                                {% end_page_has_content %}

                                {% placeholder body with RichTextarea %}
                            </div>

                        </article>
                        <!--end item-->
                    </div>
                </div>
                <!--end of row-->
            </div>
            <!--end of container-->
        </section>
    </div>
{% endblock main_container %}

src/templates/pages/menu.html
{% load pages_tags cache %}
{% if page.status %}
    <li>
        <a href="{% show_absolute_url page %}">{% show_content page "title" %}</a>
        {% if children %}
            <ul class="pl-3">
                {% for child in children %}
                    {% pages_menu child %}
                {% endfor %}
            </ul>
        {% endif %}
    </li>
{% endif %}

src/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block main_container %}
        <div class="main-container">
            <section class="space--sm">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="boxed boxed--lg boxed--border">
                                <div class="text-block text-center">
                                    <img alt="avatar" src="{{ profile.image.url }}" class="image--md" />
                                    <span class="h5">{{ profile.first_name }} {{ profile.last_name }}</span>
                                    <span>{{ profile.position }}</span>
{#                                    <span class="label">Contributor</span>#}
                                </div>
                                <div class="text-block clearfix text-center">
                                    <ul class="row row--list">
                                        <li class="col-md-4">
                                            <span class="type--fine-print block">Location:</span>
                                            <span>{{ profile.location }}</span>
                                        </li>
                                        <li class="col-md-4">
                                            <span class="type--fine-print block">Member Since:</span>
                                            <span>{{ profile.joined }}</span>
                                        </li>
                                        <li class="col-md-4">
                                            <span class="type--fine-print block">Contact:</span>
                                            <a href="mailto:{{ profile.email }}">{{ profile.email }}</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                            <div class="boxed boxed--border">
                                <h4>Vacation left</h4>
                                <div class="progress-horizontal">
                                  <span class="progress-horizontal__label h5">Days: {{ vacation.vacation_days_left }}</span>
                                    <div class="progress-horizontal__bar" data-value="{{ vacation.vacation_pecent_left }}"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>


        </div>
{% endblock main_container %}

src/templates/templatetags/small_profile.html
{{ variable }}